### ISSUE TITLE
Programmation concurrente en Java

### ISSUE THREAD

**Issue by fbeaufume** [ToulouseJug/call-for-paper#1]
## Sujet de votre conférence

Programmation concurrente en Java

### Le(s) speaker(s)

Florian Beaufumé est un architecte logiciel spécialisé en Java de 18 ans d'expérience. Consultant indépendant depuis 2007, il a travaillé pour des grands comptes, des éditeurs de logiciels, des SSII et des startups dans les domaines tels que les banques, les assurances et l'aéronautique.

### Description de votre conférence

Java ne manque pas de solutions de programmation concurrente, des plus simples telles que Thread, synchronized ou Executor, au plus avancées comme StampedLock, fork/join ou CompletableFuture. Nous allons décrire une sélection de ces solutions, les comparer et expliquer leurs cas d’utilisation.

Dans un second temps nous allons présenter les fonctionnalités complémentaires de concurrence des frameworks serveur comme Java EE et Spring : méthodes asynchrones, timer service et d'autres.

### Informations diverses
* Thème, label : Java, programmation concurrente
* Niveau de difficulté (débutant|confirmé) : confirmé
* Durée : 45 à 60 minutes
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): N.A., date déjà fixée au 23/03/2017

**Comment by davinkevin** [comment]
Description ajouté à https://www.meetup.com/fr-FR/Toulouse-Java-User-Group/events/237603924/

**Comment by davinkevin** [comment]
https://www.youtube.com/watch?v=Opf0giA1gQk
