### ISSUE TITLE
Deep Dive Kotlin: du Hello World au Bytecode

### ISSUE THREAD

**Issue by EmmanuelVinas** [ToulouseJug/call-for-paper#11]
## Sujet de votre conférence
Comment aborder un nouveau langage ?
Les uns répondent en codant, les autres en regardant son fonctionnement en détail.
Dans ce 'Deep Dive' nous vous proposons les deux !
Quoi de mieux que partir d'exemples pour découvrir les idiomes du langage.
Puis en regardant sous le capot, les fonctionnalités que nous n'avons pas (encore) en Java, ne resteront plus un mystère pour vous !

### Le(s) speaker(s)
Igor Laborie @ilaborie & Emmanuel Vinas. Développeurs Web et Mobile chez MonkeyPatch.

### Description de votre conférence
Version raccourcie de la présentation qu'on a fait à devoxx : https://www.youtube.com/watch?v=cXNGhDiQgmo
Les slides : https://ilaborie.github.io/slides/deepDiveKotlin/devoxx-fr.html#deepDiveKotlin

### Informations diverses
* Thème, label : Kotlin, Bytecode, Java
* Niveau de difficulté (débutant|confirmé) : Débutant
* Durée : 2H
* Format (slides, live-coding, les deux):  les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): avant juillet 2018

**Comment by arnaudbos** [comment]
Je pense que ce ticket peut être fermé à présent: http://www.toulousejug.org/2018/06/12/kotlin.html
