### ISSUE TITLE
Le Gros Quizz Java

### ISSUE THREAD

**Issue by ilaborie** [ToulouseJug/call-for-paper#13]
{ Veuillez remplir ce template afin d'avoir des informations sur votre proposition.
Merci de n'inclure dans le titre de cette issue que le titre de votre présentation }

## Sujet de votre conférence
{ Identique à celle du titre de l'issue }
Le Gros Quizz Java

### Le(s) speaker(s)
{ Nom, prénom, métier et autres références du / des speakers pour cette présentation }
Collectif.
Dans d'idéal faudrait 2 animateurs.

### Description de votre conférence
{ La description de votre conférence en quelques lignes... 
N'hésitez pas à intégrer un lien vers vos slides, vers les sites d'autres évènements si vous l'avez déjà présentez...}

Connaissez vous Java ? 
Dans la bonne humeur, venez jouer au Gros Quizz Java. Qui sait, vous rempartirer peut être avec un cadeau ?

### Informations diverses
* Thème, label : Java le langage, la platforme, l'ile
* Niveau de difficulté (débutant|confirmé) : tous
* Durée :  1h30
* Format (slides, live-coding, les deux): Question+slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):

**Comment by ilaborie** [comment]
Quelques précisions:

- utilisation de <https://kahoot.it/>
- une question associé à un thème, et une explication du résultat dans les slides
- on peut faire un google form pour collecter des questions/réponse, il faudra une équipe de sélection de ces questions.
- il faudrait récupérer des goodies (reste de vieux devfest, démarcher des éventuelles sponsors, ou investir dans des lots type bouteilles de vin, de bière, ...)
- faudrait 2 animateurs qui soient suffisament compétant en Java pour expliquer clairement les réponses (ou on passe le micro à l'auteur s'il est dans la salle)

**Comment by arnaudbos** [comment]
Je vais voir pour qu'on se le fasse en juin celui-ci, avant les vacances !

**Comment by arnaudbos** [comment]
On a organisé un quiz selon plus ou moins les mêmes modalités mardi soir : 

> - utilisation de <https://kahoot.it/>

- [x] Check

> - une question est associé à un thème, et il faut une explication du résultat dans les slides

- [ ] No check, on n'a pas vraiment respecté de "thème", mais chaque réponse était expliquée à l'oral

> - on peut faire un google form pour collecter des questions/réponses, il faudra une équipe de sélection de ces questions.

- [x] Check, le [formulaire est ici](http://bit.ly/toulousejug-quiz) et les contributions sont les bienvenues ! (je dis ça pour les lecteurs de passage par cette issue)

> - il faudrait récupérer des goodies (reste de vieux devfest, démarcher des éventuelles sponsors, ou investir dans des lots type bouteilles de vin, de bière, ...)

- [x] Check, on a des bouquins en cours d'expédition, des licences JetBrains, des goodies divers et variés de retours de confs, et on n'exclut pas d'acheter des lots spéciaux à l'occasion

> - faudrait 2 animateurs qui soient suffisament compétant en Java pour expliquer clairement les réponses (ou on passe le micro à l'auteur s'il est dans la salle)

- [x] Check, je pense qu'on s'est plutôt bien débrouillé avec @jzanon, et on a passé le relai aux auteurs des questions qui étaient présents pour qu'ils expliquent la réponse eux-même le cas échéant (merci @fbeaufume)

----

Je ferme ce ticket parce que je ne pense pas qu'on en fera un "talk" à proprement parlé, mais n'hésite pas (cher lecteur) à le rouvrir si besoin.
