### ISSUE TITLE
Découverte de Exercism

### ISSUE THREAD

**Issue by lidonis** [ToulouseJug/call-for-paper#16]
### Le(s) speaker(s)
Lidonis Calhau développeur

### Description de votre conférence
[Exercism](https://exercism.io) est une plateforme pour la pratique du code avec mentorat. Le site permet de s'exercer presque 50 langages. Je souhaite faire découvrir au plus grand nombre ce site que je trouve excellent.

### Informations diverses
* Thème, label : Language, Kata
* Niveau de difficulté (débutant|confirmé) : débutant
* Durée : 15min
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dès que possible

**Comment by arnaudbos** [comment]
Salut Lidonis, on prévoit une soirée le 15 janvier.
Est-ce que ça t'intéresserait de présenter ton sujet à cette date ?

**Comment by lidonis** [comment]
Salut, oui c'est très bien pour moi.
