### ISSUE TITLE
Vʌvr, le meilleur de Java aujourd'hui !

### ISSUE THREAD

**Issue by davinkevin** [ToulouseJug/call-for-paper#2]
## Sujet de votre conférence
Vʌvr, le meilleur de Java aujourd'hui !

### Le(s) speaker(s)
DAVIN Kevin, Software craftsman, Agile addict et développeurs "full-stack²". Formateur sur les technologies Java, Spring; AngularJS et Angular dans le monde front-end et Google Cloud Platform. 

### Description de votre conférence
Aujourd'hui, l'on aimerait avoir du code simple, fonctionnel et représentant le besoin plutôt que des éléments techniques. Vʌvr est un ensemble d'API qui va rendre votre code "beau". L'on fera un tour des différents éléments présent dans Vʌvr et mon retour d'expérience, puisque je les utilise tous les jours ! 

### Informations diverses
* Thème, label : Java, Functional, Lib
* Niveau de difficulté (débutant|confirmé) : Débutant
* Durée : ~30m
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): pas avant septembre

**Comment by arnaudbos** [comment]
@davinkevin la dernière fois qu'on en a discuté tu semblais dire que tu n'avais plus trop le temps/l'intérêt de faire cette présentation.
@orevial est-ce que tu serais tenté pour reprendre le flambeau ?

**Comment by davinkevin** [comment]
Je ne fais plus de VAVR ni de Java en ce moment... donc je serai mal placé
pour le faire je pense. (Kotlin ❤️)

Et ensuite avec ce que Daniel Dietrich annonce pour la v1, je suis un peu
refroidi 😛

Par contre, aucun problème pour "aider" @orevial si nécessaire (même si je
pense qu'il doit pas en avoir besoin)

Le mer. 21 nov. 2018 à 15:07, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
@agrison prend la relève dee ce talk et nous parlera du livre qu'il a écrit à ce sujet !

**Comment by arnaudbos** [comment]
Merci @davinkevin !

**Comment by davinkevin** [comment]
De rien, je fais du ménage dans mes issues ouvertes et celle ci ne me semblait plus très utile :D
