### ISSUE TITLE
La programmation fonctionnelle sans céder à la mode

### ISSUE THREAD

**Issue by fcabestre** [ToulouseJug/call-for-paper#20]
## Sujet de votre conférence
La programmation fonctionnelle sans céder à la mode

### Le(s) speaker(s)
Frédéric Cabestre

### Description de votre conférence
Aujourd'hui, pour être à la mode, il faut parler de programmation fonctionnelle. Et de suite on convoque les mots en vogue: « *Immutabilité* », « *Monade* » ou « *Catamorphisme* ». Au mieux le message est brouillé, mal reçu. Au pire la salle se vide ! 

Ce que je vous propose c'est de repartir des principes de base, avec des idées bien arrêtées et peut-être parfois provocatrices. Comprendre, comme le disait **John Hugues**, « *Why functionnal programming matters* ». Cerner les quelques idées directrices de la programmation fonctionnelle et ce qu'elles apportent concrètement au quotidien. Voir comment et pourquoi d'autres concepts en découlent nécessairement...

Il sera peut-être finalement question de « *Théorie des catégories* » ! Mais il sera surtout question, en vrac, d'histoire et de mise en œuvre des langages, de typage, de performance, d'artisanat du logiciel, de « *Design patterns* », d'abstraction et, soyons fou, de *réification*. 

En somme, je vais vous parler de programmation fonctionnelle en essayant de ne pas être à la mode !

### Informations diverses
* Thème, label : Programmation fonctionnelle
* Niveau de difficulté (débutant|confirmé) : intermédiaire
* Durée : < 1 heure
* Format (slides, live-coding, les deux): transparents + code (mais pas de live coding ! )
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): Yolo

**Comment by arnaudbos** [comment]
Ça te dirais de prévoir ça pour début mai ? Quelque chose me dit que ta présentation, sans le live coding, suivie d'un exemple pratique via le sujet #27 de notre ami @enhan pourrait nous faire une soirée des plus charmantes.
J'ai juste peur que 2 * 1h ce soit beaucoup à encaisser donc à voir si vous avez vraiment besoin d'une heure entière chacun.

**Comment by fcabestre** [comment]
Ouaïe note. Si je dois faire 40 minutes, voire 30, je peux élaguer... Mais pas la partie de code finale qui est sensée exemplifier l'essence de ce que je veux raconter :smile:.

**Comment by arnaudbos** [comment]
On va faire simple, parce que j'ai envie d'avoir une belle soirée sur ce thème : on part sur 1h, si tu fais moins pas de soucis mais interdiction de dépasser :slightly_smiling_face: et idem pour @enhan s'il est chaud pour mai.
