### ISSUE TITLE
Easy Kafka comprendre les concepts et jouer avec facilement

### ISSUE THREAD

**Issue by kenji-getpowered** [ToulouseJug/call-for-paper#21]
Kafka, le prendre en main et jouer avec !

## Sujet de votre conférence
Kafka Starter Kit : marre de revoir les mêmes conférences et envie de mettre les mains dans le cambouis facilement?  On vous propose une révisions des concepts (donc débutant accepté) puis de d'utiliser notre framework pour démarrer kafka en mode test unitaire.

### Le(s) speaker(s)
Mikael KROK; Dev (java entre autre) et Scrum Master chez Cegedim Insurance Solution > The speaker
Romain Chartier : Architecte chez Cegedim Insurance Solution >  The brainiac

### Description de votre conférence
On montre les concepts puis on montre notre framework qui permet de lancer kafka dans les tests unitaires > on évite les soucis de persistance des messages et on commence à mieux saisir les concepts.

### Informations diverses
* Thème, label :
* Niveau de difficulté  débutant ++
* Durée :  1H 
* Format: Slides + Live coding
* Dispo : fin janvier

**Comment by kenji-getpowered** [comment]
Oups,on propose bien un talk d'1h et pas d'1 jour :)

**Comment by arnaudbos** [comment]
Salut Mikael, on prévoit une soirée le 15 janvier : pour la rentré :smile: 
Est-ce que ce serait bon pour vous deux ou c'est trop tôt ?

**Comment by kenji-getpowered** [comment]
C'est trop juste pour nous. Le sujet est pas encore sec sec. Fin janvier
début février c'est mieux.

Le mer. 12 déc. 2018 à 14:03, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Pas de soucis je comprends.

La soirée de février est déjà bouclée, il faudra programmer ça une autre fois alors :slightly_smiling_face:

**Comment by kenji-getpowered** [comment]
Dommage c'est quoi les autres dates?

Le mer. 12 déc. 2018 à 17:07, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Pour l'instant on se fixe une fois par mois, donc ce serait mars, puis avril, etc., le temps que je JUG reprenne du poil de la bête surtout !  
Ensuite qui sait, peut-être que d'ici quelques mois on augmentera la fréquence :smile:

**Comment by kenji-getpowered** [comment]
Ok,

Bon je vois avec mon collègue pour voir si on serait prêt pour le 15 et je
te dis ça avant la in de la semaine.

Il faut surtout qu'on finalise notre starter kit.


Le mer. 12 déc. 2018 à 17:11, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Ok ça marche !  
Vous mettez pas trop la pression, je sais ce que c'est ce genre de préparation.

Je contacte d'autres personnes qui ont proposé au CfP pour optimiser l'organisation mais on prend pas de décision avant samedi le temps d'avoir ton retour :wink:

**Comment by kenji-getpowered** [comment]
Hello

Bon, on sera jamais prêt pour le 15 mais comptez sur nous pour mars.

Est ce que ça vous va ?

Le mer. 12 déc. 2018 à 17:45, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Pas de soucis !  
Je crée le milestone de mars et je vous rajoute dessus, merci de m'avoir tenu au courant  
rapidement 🙂  
Du coup je vais essayer d'axer la soirée de janvier sur du test.

Je reviens vers vous début février pour la logistique et pour la date précise. D'ailleurs vous avez déjà une préférence ou la semaine 10 par exemple ça vous irait ?

**Comment by kenji-getpowered** [comment]
Ok pour nous!

Go pour la semaine 11, wouhou!

Le dim. 16 déc. 2018 à 06:21, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
J'avais calé le [milestone de mars](https://github.com/ToulouseJug/call-for-paper/milestone/4) le 12 mars un peu au pif mais je pense qu'on peut la garder cette date, est-ce que ça vous convient ?

**Comment by arnaudbos** [comment]
Je vous fais passer en premier avec pour consigne de ne pas dépasser l'heure, comme ça @MounirReg pourra clôturer la soirée avec son sujet #26.

**Comment by kenji-getpowered** [comment]
Ok pour le 12 mars.


Le jeu. 17 janv. 2019 à 16:21, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by kenji-getpowered** [comment]
Hello mon co présenter est à l'étranger la semaine du 12 peut on le faire
le 19?

**Comment by MounirReg** [comment]
Pas d'objection de mon côté

**Comment by arnaudbos** [comment]
Ok pour le 19 :-)

**Comment by arnaudbos** [comment]
Prêts pour la semaine prochaine @kenji-getpowered @MounirReg ?

**Comment by MounirReg** [comment]
Yes :)

**Comment by kenji-getpowered** [comment]
oui

Un peu compliqué finalement de faire tenir sur une heure  mais bon on va y
arriver :p

Le lun. 11 mars 2019 à 16:25, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by maelvalais** [comment]
Le talk était super !
J'ai entendu parler d'un dépôt gitlab pour le projet que vous avez open-sourcé pendant la présentation mais pas eu le temps de le noter 🙄
Merci pour votre présentation !!

**Comment by arnaudbos** [comment]
@kenji-getpowered si tu tweet un lien le truc en mentionnant le JUG (pour que je le retrouve), je pourrai le relayer également.

**Comment by kenji-getpowered** [comment]
Hello, le tweet est a été tweeté :)
https://twitter.com/mikaelkrok/status/1110212509364039681


Le jeu. 21 mars 2019 à 12:18, Arnaud Bos <notifications@github.com> a
écrit :
