### ISSUE TITLE
GraalVM : les applications natives en Java

### ISSUE THREAD

**Issue by swallez** [ToulouseJug/call-for-paper#22]
## Sujet de votre conférence
GraalVM : les applications natives en Java

### Le speaker
Sylvain Wallez, Tech lead, Elastic

### Description de votre conférence
GraalVM est une JVM nouvelle génération qui a plusieurs aspects intéressants :
* elle est "polyglotte" et permet de faire tourner du Java/Kotlin/Scala (classique) mais aussi du R, JavaScript, Ruby ou Python (moins classique)
* elle permet de faire de la compilation "ahead of time" et produire un exécutable natif minimaliste qui peut être déployé facilement.

La présentation montrera les différentes capacités de GraalVM et comment la compilation native permet de répondre aux contraintes des applications "cloud-native", catégorie qui regroupe les micro-services, le serverless, les containers (et side-cars), etc.

### Informations diverses
* Thème, label : JVM
* Niveau de difficulté (débutant|confirmé) : débutant
* Durée : 45 min
* Format (slides, live-coding, les deux): Slides + démo
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dispo

**Comment by arnaudbos** [comment]
Ça te dirais de faire ça en avril ? J'ai pas encore de date fixe à te proposer.
C'est cette propal qui as reçu le plus de 👍 pour le moment, donc ce serait cool de la programmer dans pas trop longtemps mais les soirées de [février et mars](https://github.com/ToulouseJug/call-for-paper/milestones) sont déjà bookées.

**Comment by arnaudbos** [comment]
Je te propose le jeudi 4 ou le mardi 9 avril. Tiens moi au courant :)

**Comment by swallez** [comment]
Hmm... Il y a eu du nouveau sur la dispo : c'est la semaine avant Devoxx. Si mon talk est accepté, je serai en phase de stress montant pour la préparation...

Et en mai, je serai en déplacement du 6 au 17 mai.

Mais avoir le plus de 👍 avec 4 votes, IMHO ça nécessite de faire un appel aux votants sur la liste du JUG histoire d'avoir un panel plus large !

**Comment by arnaudbos** [comment]
Je sais pas ce que tu as proposé à Devoxx mais c'est justement parce que c'est la semaine juste avant qu'Igor a proposé le sien au JUG, pour répéter. Mais ça a l'air chaud côté dispo de ton côté donc pas de soucis on peut le programmer une prochaine fois, j'ai le temps de trouver autre chose pour compléter la soirée d'avril :wink:

Sinon je pense pas qu'on aura beaucoup de :+1:, même le GDG qui brasse des foules à chaque soirée en a seulement 7 sur ses talks les mieux notés...

**Comment by jzanon** [comment]
Avec la hype autour de Quarkus.io je pense que ce sujet est pourrait intéresser du monde.

**Comment by arnaudbos** [comment]
On est à 9 :+1:, pour moi ça veut dire qu'on peut le programmer.  
En ce qui me concerne pour septembre j'hésite entre celui-ci, celui sur le GC et le Rust (par @magnet). @swallez faut que tu nous dises si tu serais dispo en septembre, et lequel tu préférerais faire GraalVM ou War story ?

On pourra pas faire le Rust la même soirée, il faut un truc plus court, mais par contre si Sylvain n'est pas dispo on peut essayer de le caser avec autre chose (de très court).

**Comment by swallez** [comment]
Dispo en septembre ! Et après quelques discussions à DevoxxFR, il semble que GraalVM intéresse plus que la war story sur le GC. Pas vrai @davinkevin ? 😉

**Comment by davinkevin** [comment]
Je suis peut être pas représentatif, mais il est vrai que le fonctionnement sous-jacent de GraalVM m’intéresse et que je voie que cela est en train de chambouler l’état du monde Java/JVM

**Comment by pgillet** [comment]
Hello @swallez, j'ai également un sujet sur GraalVM que j'essaie de pousser en parallèle dans des conférences (je n'ai rien de prêt pour l'instant!). Outre les aspects performances, je suis particulièrement intéressé par le côté polyglotte de GraalVM. Mon sujet tel que je le propose:
***

*“Cette librairie n'est pas disponible dans mon langage de programmation. Je dois la réécrire."*

*"Ce langage conviendrait parfaitement à mon problème, mais nous ne pouvons pas l'exécuter dans notre environnement."*

*"Ce problème est déjà résolu dans tel ou tel langage, mais ce langage est trop lent."*

Début 2019, Oracle enchaîne les Release Candidates pour la version 1.0 de **GraalVM**, une extension de la JVM HotSpot.
Le 1er objectif de GraalVM  est d'améliorer les **performances** des langages JVM tels que Groovy, Scala ou Kotlin pour égaler les performances des langages natifs.😛

Le 2ème objectif de GraalVM est d'offrir un ***runtime*** **partagé** pour exécuter des langages *invités*: JavaScript et Node.js, C, C++, Rust, Ruby, R et Python sont tous de la partie!😲

L'autre grand objectif de GraalVM est de mélanger librement tous ces langages dans des applications multi-langages ou **polyglottes**: imaginez une application dont le code source mêle le Java, le JavaScript, le Python, et le Rust!🤯  
GraalVM fournit un moyen de passer des valeurs de variables d'un langage à l'autre, sans copie ou encapsulation comme dans d'autres systèmes. GraalVM permet donc aux développeurs de choisir librement le bon langage pour la tâche à résoudre, sans faire de compromis sur les performances.

Dans cette présentation, nous allons étudier les mécanismes de GraalVM permettant des applications polyglottes. Nous présenterons également Truffle, un outil associé à GraalVM pour écrire son propre langage.

Et bien sûr nous écrirons, en live, une application multi-langages!

***
Bien sûr, je ne veux pas faire doublon avec toi: je proposerai mon sujet ici que si tu n'as pas le temps, plus l'envie, etc. 
Qu'en penses-tu?

Je suis également preneur de conseils et/ou remarques sur comment orienter un tel sujet...

**Comment by arnaudbos** [comment]
@orevial le papier dont je t'ai parlé hier : [Practical partial evaluation for high-performance dynamic language runtimes](http://chrisseaton.com/rubytruffle/pldi17-truffle/pldi17-truffle.pdf). Très abordable et bien écrit.

Novembre me semble, à priori, un bon moment pour programmer l'un de vous deux.

**Comment by swallez** [comment]
@pgillet je voulais me concentrer exclusivement sur la partie concernant les langages de la JVM (Java, Scala, Kotlin) parce que de mon point de vue c'est l'application de GraalVM qui a le plus de répercussion sur notre industrie et permet à Java de rester pertinent dans un monde de micro-services/serverless où la bonne grosse JVM, qui était adaptée à des serveurs d'applications, n'est plus pertinente.

Côté perfs, GraalVM améliore certainement les choses pour les langages interprétés, mais pas forcément pour les langages JVM où la HotSpot fait un travail d'optimisation très poussé. Les grosses différences se trouvent sur le temps de démarrage et l'empreinte mémoire.

J'avoue être assez dubitatif sur l'utilité de l'aspect polyglotte. Est-ce que ça a vraiment un intérêt de mélanger plusieurs langages dans un unique process ? Est-ce que ça n'est pas vue de l'esprit matérialisée en prouesse d'ingénierie ? Je ne demande évidemment qu'à être convaincu avec des vrais use cases 😉

**Comment by arnaudbos** [comment]
Digression à part et même si je trouve le sujet très intéressant, j'ai l'impression que @swallez est toujours chaud pour une présentation, @pgillet. Mais je n'ai aucun soucis avec le fait que deux talks sur le même sujet soient proposés par deux personne différentes.

Sauf si tu préfères réorienter ton talk à la lumière de ce que vient de dire Sylvain (et je ne dis pas que c'est ce qu'il faut, ou ne faut pas faire), j'ai l'impression que les deux approchent le sujet sous deux angles différents. Et c'est assez cohérent avec l'envergure du projet (SDK, compiler, Truffle, Substrate, etc).

Sachez tout de même que si vous proposez tous les deux un talk sur GraalVM, et même s'ils sont différents, j'aurai du mal à planifier les deux à moins de plusieurs moins d'intervalle.

J'aurai plutôt tendance à favoriser Sylvain si je recherche un speaker plus expérimenté pour une soirée en particulier, et plutôt Pascal si l'aspect polyglotte colle plus au thème ou si je veux favoriser les tours de parole.  
Pour info, à l'instant T je me dis qu'un talk sur GraalVM en novembre pourrait être cool mais j'ai pas plus de billes que ça donc absolument rien n'est joué.

Autre solution : un talk à deux voix :slightly_smiling_face:

**Comment by swallez** [comment]
Ah oui oui, toujours chaud ! Et le talk à 2 voix, ou une soirée GraalVM en 2 parties qui aborde les 2 sujets qui comme tu le dis ont des axes complémentaires pourrait à mon avis être une bonne approche.

Genre "GraalVM, la renaissance de Java pour les micro-services" et "GraalVM, pour des applications polyglottes performantes". Et comme ça on a un vieux ~sage~singe et un padawan en progression. Parce qu'on ne devient expérimenté qu'en pratiquant !

**Comment by arnaudbos** [comment]
Sounds like a plan.

**Comment by pgillet** [comment]
L'idée de 2 talks sur GraalVM, tels que présentés par @swallez , est séduisante. Je me concentrerais donc plus sur l'aspect polyglotte, même si, j'en suis conscient, cela relève plus d'un produit de laboratoire.

Question pratique et vu avec @arnaudbos : je risque d'être full jusqu'à mi-novembre, donc une session début décembre serait l'idéal pour moi. 2 talks séparés à 1 ou 2 mois d'intervalle me paraît tout aussi bien qu'une soirée complète sur le sujet: cela crée du teasing (pour moi seulement :grimacing:)

**Comment by swallez** [comment]
De mon côté, dispo uniquement après le 3 octobre. D'ici la je fais de la [musique en JavaScript](https://devfesttoulouse.fr/sessions/live_coding_musical___vous_savez_coder___devenez_compositeur_avec_webaudio_et_webmidi__/) 😄

**Comment by arnaudbos** [comment]
Hello vous deux,
J'aimerais programmer vos deux talks sur une soirée pour faire un méga-combo !

@pgillet je crois savoir qu'il sera difficile pour toi d'être dispo en Novembre ?
Est-ce que début décembre ça collerait mieux ?

@swallez même question, est-ce que tu serais dispo début décembre ?

A plus !

**Comment by swallez** [comment]
Ok pour moi en décembre !

**Comment by pgillet** [comment]
Ok aussi

**Comment by pgillet** [comment]
:+1:

**Comment by arnaudbos** [comment]
Deal, la salle est bookée, merci à vous :-)

**Comment by arnaudbos** [comment]
@pgillet si tu as un titre pour ta préz, je prends ;)

**Comment by pgillet** [comment]
### GraalVM: ja JVM polyglotte

*“Cette librairie n'est pas disponible dans mon langage de programmation. Je dois la réécrire."*

*"Ce langage conviendrait parfaitement à mon problème, mais nous ne pouvons pas l'exécuter dans notre environnement."*

*"Ce problème est déjà résolu dans tel ou tel langage, mais ce langage est trop lent."*

Oui, GraalVM améliore les performances des langages JVM tels que Groovy, Scala ou Kotlin pour égaler les performances des langages natifs. Oui, GraalVM permet de produire des exécutables Java standalone - des images natives - grâce à la compilation Ahead-of-time. Oui, le startup de ces applications est grandement réduit. Oui, GraalVM est bien intégrée dans des frameworks tels que Micronaut et Quarkus. Et donc oui, GraalVM rend ses lettres de noblesse au langage Java, qui devient très pertinent dans le monde des micro-services. 😛

Dans ce talk, nous nous intéresserons à l'autre grand objectif de GraalVM, qui est de mélanger librement plusieurs langages dans des applications multi-langages ou **polyglottes**: imaginez une application dont le code source mêle le Java, le JavaScript, le Python, et le Rust! 🤯  GraalVM permet donc aux développeurs de choisir librement le bon langage pour la tâche à résoudre, sans faire de compromis sur les performances.

Nous allons étudier les mécanismes de GraalVM permettant des applications polyglottes. Nous présenterons également Truffle, un outil associé à GraalVM pour écrire son propre langage.

Et bien sûr nous écrirons, en live, une application multi-langages!

**Comment by arnaudbos** [comment]
@swallez & @pgillet pouvez-vous me partager vos slides por favor? J'attaque les vidéos !

**Comment by pgillet** [comment]
Here we are! Merci encore pour cette soirée.

[GraalVM.pdf](https://github.com/ToulouseJug/call-for-paper/files/4025408/GraalVM.pdf)

[GraalVM.zip](https://github.com/ToulouseJug/call-for-paper/files/4025409/GraalVM.zip)

**Comment by swallez** [comment]
Les miennes sont ici: https://docs.google.com/presentation/d/1-hT1pJBskehoJ50_5bDCrYug0w_Nj_NbP7Chdk7hTcY/edit

Dis-moi si tu veux un autre format (PDF & co).

**Comment by arnaudbos** [comment]
C'est parfait, merci à vous !
