### ISSUE TITLE
Log structurés : enfin des logs utilisables

### ISSUE THREAD

**Issue by swallez** [ToulouseJug/call-for-paper#23]
## Sujet de votre conférence
Log structurés : enfin des logs utilisables

### Le(s) speaker(s)
Sylvain Wallez, Tech lead, Elastic

### Description de votre conférence
Les logs sont (trop) souvent du texte non structuré dans lesquels on cherche, parfois vainement, à grands coups de `grep`.

Pourquoi ne pas plutôt produire un format structuré comme du JSON, avec des champs bien définis, de façon a faciliter la recherche et l'extraction de statistiques ?

Nous verrons comment étendre Logback pour produire du JSON, et aussi comment ajouter aux classiques timestamp/sévérité/messages des valeurs applicatives décrivant formellement le contexte du message.

### Informations diverses
* Thème, label : Java, logs
* Niveau de difficulté (débutant|confirmé) : débutant
* Durée : 45 min
* Format (slides, live-coding, les deux): slides et démo
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dispo

**Comment by arnaudbos** [comment]
C'est toujours d'actualité ça @swallez ? Je fais un peu de ménage, n'hésite pas à le fermer si non.

**Comment by swallez** [comment]
Ouh c'est vieux ça ! Maintenant il faudrait plutôt parler de OpenTelemetry, traces, spans et distrubuted tracing (avec Elastic, bien évidemment). Je ferme, même si le thème reste intéressant.
