### ISSUE TITLE
🏋️‍♂️ Refactoring sans les `for`

### ISSUE THREAD

**Issue by ilaborie** [ToulouseJug/call-for-paper#24]
{ Veuillez remplir ce template afin d'avoir des informations sur votre proposition.
Merci de n'inclure dans le titre de cette issue que le titre de votre présentation }

## Sujet de votre conférence
🏋️‍♂️ Refactoring sans les `for`

### Le(s) speaker(s)
Igor

### Description de votre conférence
Peut-on se passer de la bonne vieille boucle `for` ?
Il est toujours intéressant de creuser les alternatives comme les `Stream`, ou d'autres options.
Mais le plus important c'est de savoir quand il fuir cette instruction. Ou pas !

Au quotidien, les boucles sont les briques de base de notre code.
Mais on oublie souvent les alternatives comme l'API `Stream`, la récursivité...
C'est toujours bénéfique de prendre du recul sur le code que l'on écrit, pour analyser ce qui peut être amélioré.
Les alternatives sont elles plus lisibles ? Plus maintenables ? Plus performantes ?

Ici on se contentera de regarder ce qui se passe en Java, avec quelques incursion coté Kotlin et Scala.
Mais le propos s'adapte aux autres langages de programmation.

### Informations diverses
* Thème, label : loop, stream, recursion, perf
* Niveau de difficulté (débutant|confirmé) : Tous
* Durée : 45-60min
* Format (slides, live-coding, les deux): plutôt des slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): 

J'ai proposé ce talk à quelques conférences, donc l'idéal ce serait juste avant la première conf qui m'acceptera. Mais ça peut se faire après

**Comment by arnaudbos** [comment]
Le planning pour janvier/février et mars s'est assez vite rempli contre toute attente, du coup tiens moi au courant de comment ça avance de ton côté question conférences et on essayera de trouver un créneau avant, dans la mesure du possible 😉

**Comment by arnaudbos** [comment]
On dit avril du coup ?

**Comment by ilaborie** [comment]
Oui, si c'est avant le 15 avril

**Comment by arnaudbos** [comment]
On va voir pour le 4 ou le 9 avril, je te tiens au courant suivant les disponibilités de @swallez pour caler sa présentation #22 le même soir (et suivant la dispo de l'amphi d'Epitech).

**Comment by arnaudbos** [comment]
J'ajoute #32 (30mn) au milestone pour compléter la soirée.

OK pour le 4 avril tous les deux @ilaborie @orevial ?

**Comment by ilaborie** [comment]
Ok

**Comment by orevial** [comment]
> J'ajoute #32 (30mn) au milestone pour compléter la soirée.
> 
> OK pour le 4 avril tous les deux @ilaborie @orevial ?

Ok aussi

**Comment by swallez** [comment]
Talk fait le 4 avril 2019
