### ISSUE TITLE
Java et les Jeux Vidéo

### ISSUE THREAD

**Issue by MounirReg** [ToulouseJug/call-for-paper#25]
### Le(s) speaker(s)
Mounir Regragui, Software Engineer

### Description de votre conférence
A l'heure où les frameworks de développement de jeux-vidéo les plus populaires sont Unity et UE, la conférence proposera de :

* Revenir sur les plus grands jeux codés en Java (Minecraft, mais pas que)
* Présentation rapide du framework LibGdx, et si il y a le temps, une petite session de live coding basique

### Informations diverses
* Thème, label : Jeux-vidéo
* Niveau de difficulté : Tous publiques
* Durée : 30 minutes à 1 heure en fonction du scope
* Format : Slides (+ live coding)
* Dispo ou indispo : Je ne serai pas dispo du 15/05 au 07/06

**Comment by arnaudbos** [comment]
Pour info : https://www.reddit.com/r/gamedev/comments/epkd31/engines_used_in_the_most_popular_games_of_2019/
😉

**Comment by MounirReg** [comment]
Nice! Par contre ca compte pas les engines "maison" :)

Le ven. 17 janv. 2020 à 11:41, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
En effet !

**Comment by arnaudbos** [comment]
Je te rajoute au milestone de février ! 😉
