### ISSUE TITLE
Introduction à la Programmation Orientée Aspect

### ISSUE THREAD

**Issue by MounirReg** [ToulouseJug/call-for-paper#26]
## Sujet de votre conférence
Introduction à la Programmation Orientée Aspect

### Le(s) speaker(s)
Mounir Regragui

### Description de votre conférence
Présentation de la programmation orientée aspect : concepts, vocabulaires, exemples avec AspectJ/Spring et CDI

### Informations diverses
* Thème, label : Dev
* Niveau de difficulté (débutant|confirmé) : Débutant, confirmé
* Durée : 30 minutes
* Format (slides, live-coding, les deux): Les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): Pas dispo entre le 15/05 et 07/06

**Comment by arnaudbos** [comment]
Salut, merci pour la proposition. C'est un sujet qui est trop peu souvent abordé je trouve donc ça m'intéresserait de le programmer.
On a un créneau en mars si ça te tente, en complément du #21 qui va durer 1h.
La soirée de février est bookée et je suis en train de planifier celles d'avril/mai avec d'autres sujets donc ça repousserait en juin, où on pourrait d'ailleurs essayer de caler le #13 si on arrive à l'organiser...
Tiens moi au courant 😃

**Comment by MounirReg** [comment]
Salut Arnaud!
Pour moi le créneau de mars est ok. Je peux aussi jouer sur la durée du
live coding pour moduler la durée de la présentation.

A+

Mounir

**Comment by arnaudbos** [comment]
Super, va pour mars ! Tu peux partir sur 30 minutes, je te ferai passer en second pour mettre une contrainte "forte" de timing au talk Kafka #21, pour ne pas qu'ils dépassent l'heure, donc à toi de voir si tu veux déborder un peu pour du live-coding bonus, et ensuite pizzas :smiley:

**Comment by MounirReg** [comment]
Très bien :)

**Comment by arnaudbos** [comment]
Je n'ai pas trouvé de photo de toi en ligne. Si ça t'intéresse tu peux m'envoyer un jpeg ou un lien par mail (visible sur mon profile normalement) pour que je l'utilise sur les slides d'intro de la session et pour l'intro de la vidéo youtube.  
Pour le moment j'ai mis [juggy](https://pbs.twimg.com/profile_images/1276625408/avatar_400x400.JPEG) en placeholder.
