### ISSUE TITLE
De l'OOP à la FP : l'affaire de la validation

### ISSUE THREAD

**Issue by enhan** [ToulouseJug/call-for-paper#27]
### Emmanuel Nhan
Développeur Backend chez Sigfox.

### Abstract:
On est tous tombé au moins une fois dans cette boucle en remplissant un formulaire web :

 * Remplir et cliquer sur envoyer,
 * Avoir en retour un champ en erreur,
 * Corriger la saisie et soumettre,
 * Avoir un autre champ en erreur,
 * Corriger la saisie et soumettre,
 * ...

Même chose pour l'envoi d'une requête HTTP avec un body JSON qui peut être invalide à plusieurs endroits. Doit-on corriger chaque champ un à un à mesure que l'on découvre les erreurs ou existe-t-il un moyen d'avoir l'ensemble des erreurs dès la première requête ?

Dans ce talk, nous examinerons les moyens pour remonter toutes les erreurs dès la première validation en commençant par la solution la plus Java possible en utilisant la JSR 303 Bean Validation. Après avoir vu les avantages et inconvénients de cette approche, nous essayerons de construire un programme plus fonctionnel. Petit à petit nous ferons émerger des abstractions et nous déboucherons sur une version purement fonctionnelle de la résolution de ce problème.

Ce talk est fait pour les développeurs Java ou Kotlin qui veulent rendre leur code plus fonctionnel. Par conséquent, il nécessite une connaissance de Java et des bases de Kotlin ou Scala. Si vous connaissez déjà Scala et Cats, ne vous attendez pas à apprendre beaucoup.

### Informations diverses
* Thème, label : Paradigmes FP/OOP
* Niveau de difficulté (débutant|confirmé) : confirmé
* Durée : 1h
* Format (slides, live-coding, les deux):  les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):  à partir de début mai.

**Comment by arnaudbos** [comment]
See https://github.com/ToulouseJug/call-for-paper/issues/20#issuecomment-454966228

**Comment by arnaudbos** [comment]
Tu serais motivé pour faire ta présentation début mai ? Avec en première partie la présentation de @fcabestre, ça nous ferait une soirée du tonnerre !

**Comment by enhan** [comment]
@arnaudbos Vendu ! Faudra prévoir le paracetamol avec les pizzas :)
