### ISSUE TITLE
War story : comment les pauses du GC ont pété la prod

### ISSUE THREAD

**Issue by swallez** [ToulouseJug/call-for-paper#28]
## Sujet de votre conférence
War story : comment les pauses du GC ont pété la prod

### Le(s) speaker(s)
Sylvain Wallez

### Description de votre conférence
Nous avons eu un [incident récent sur Elastic Cloud](https://www.elastic.co/blog/elastic-cloud-january-18-2019-incident-report) dont une des causes est des pauses longues du garbage collector de ZooKeeper.

Le talk présentera les grands principes de ZooKeeper et comment il est utilisé sur Elastic Cloud. On verra comment du code apparemment juste sous-optimal dans la librairie Apache Curator a en fait contribué à une réaction en chaîne qui a mis par terre une partie des services, et comment nous y avons remédié pour que ce type d'incident ne se produise plus.

### Informations diverses
* Thème, label : JVM, garbage collector, systèmes distribués
* Niveau de difficulté (débutant|confirmé) : débutant
* Durée : 45 min
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): à partir de mi-mai 2019

**Comment by arnaudbos** [comment]
Hello Sylvain, j'ai proposé à @fbeaufume un créneau en Janvier pour parler de [GraphQL](https://github.com/ToulouseJug/call-for-paper/issues/34) et je te propose soit d'être le plan B avec ce talk, si Florian n'est pas dispo, soit de te programmer directement en février.
Le sujet est dans le backlog depuis un sacré bail et que tu es à fond sur Rust en ce moment, mais je pense que ce retour d'expérience peut être super enrichissant.
Du coup est-ce que ça te tente ?

**Comment by swallez** [comment]
@arnaudbos +100 pour faire le talk ! Rust m'excite beaucoup c'est vrai, mais Java reste une partie importante de mon activité, et puis là on va parler d'architecture système, de résilience, de back-pressure, de files d'attente, sujets applicables à beaucoup d'environnements.

**Comment by fbeaufume** [comment]
Salut. Je dois décliner de mon coté, pas la dispo en ce moment pour MAJ ma présentation. Dans tous les cas j'aurai grand plaisir à assister à cette présentation de Sylvain.

**Comment by swallez** [comment]
Elle est si importante que ça la MAJ ? Moi il faut que je construise la présentation !

**Comment by arnaudbos** [comment]
@fbeaufume merci pour le feedback, on reboucle ensemble dans les commentaires sous ton sujet 😉 

Ok @swallez je te cale dans le milestone de Janvier !
Je sais pas encore trop quelle date te proposer. Le 5/12 t'en dis quoi ?

/cc @jzanon

**Comment by fbeaufume** [comment]
J'ai l'application d'exemple à reprendre car le framework évolue. Et puis j'aimerais aller un peu plus loin (sécurité, notifications push).

Ah oui aussi il y a les slides à écrire. :)

**Comment by arnaudbos** [comment]
@swallez je ne sais plus par quel canal tu m'avais dit que tu ne serais plus disponible après la mi-janvier, alors je recentre la discussion ici. Est-ce que le 7 janvier ce serait bon pour toi ?

**Comment by swallez** [comment]
@arnaudbos oui, pas dispo entre le 21 et 31 janvier. Le 7 ça me va, ça peut aussi être le 14 si on reste sur des jeudi.

**Comment by swallez** [comment]
On fait ça quand alors ? Le 14 permettrait peut-être de laisser plus de temps pour les annonces que le 7 ?

**Comment by arnaudbos** [comment]
Bonne idée ! @jzanon ok pour toi ?

**Comment by jzanon** [comment]
Oui carrément. Surtout que j'ai une rentrée chargée 🙂

Le 14/01 donc.

**Comment by arnaudbos** [comment]
J'ai réservé le créneau pour le crowdcast, je m'occupe du meetup et des annonces demain. Bonne fin de weekend 🙂
