### ISSUE TITLE
Rust pour les développeurs Java

### ISSUE THREAD

**Issue by magnet** [ToulouseJug/call-for-paper#29]
### Speaker

Simon Chemouil, un développeur freelance, qui a passé les 10 dernières années à développer en Java et à se spécialiser sur la JVM, et qui a émigré vers Rust il y a 6 mois.

### Description

Rust, tout comme Java, est né de l'objectif de proposer une alternative sûre à C++ (à l'exécution et pour la santé mentale des développeurs :hurtrealbad: ), mais avec une approche radicalement différente: du côté de Java, la sûreté résulte de la VM et de son Garbage Collector, alors que Rust est le premier langage mainstream à proposer un mécanisme sûr de gestion automatique de la mémoire "compile-time", tout en générant des binaires natifs. Le Rust atteint ainsi la performance de C/C++ sans les risques associés.

Dans cette présentation, il sera question de présenter Rust en partant de Java, en comparant le modèle mémoire, les primitives de design, la gestion des erreurs et le multi-threading.

Après une brève présentation "Rust par rapport à Java", où principalement seront comparés le GC de Java et le borrow checker de Rust (10 slides, ~20 mins), on ira tout droit dans le code en portant du code écrit en Java vers Rust, en comparant les points forts des deux langages. 

Il s'agit d'un talk d'introduction, modérément technique, le code Java qui sera porté sera trivial (aucun framework, mais multi-threadé), et promis à la fin Duke et Ferris vont pas se taper dessus :coffee: :heart: :crab: 

### Informations diverses

* Connaissances requises: Java, le GC, le multi-threading en Java (API Thread, synchronized et ConcurrentHashMap)
* Niveau de difficulté : progressif :rofl: 
* Durée : 1h ± 5 minutes
* Format : 20mins slides || 40 ±5mins live-coding 
* Dispo ou indispo : dès que possible, pas entre le 1 et le 15 avril, de préférence avant l'été

**Comment by arnaudbos** [comment]
Hello. On a eu un peu de mal à te programmer plus tôt, désolé.  
Est-ce que le 7/11 t'intéresserait ?

**Comment by magnet** [comment]
Hello, ça marche !

**Comment by arnaudbos** [comment]
No problemo !  
Donne moi juste une durée approximative que je vois quel autre talk je peux prévoir pour compléter la soirée et ça roule :-)

**Comment by magnet** [comment]
Je vais viser vers 1h mais j'aimerais avoir 15 minutes de rab pour finir proprement si jamais. 
Ça fait un long talk mais il y a des concepts clef sur lesquels il faut rester un peu, et pour comparer avec Java il faudra expliquer un peu comment ça se passe en comparaison sur la JVM et sur les langages principaux qui la ciblent.

**Comment by arnaudbos** [comment]
Accordé ! 1h15 it is. Manque plus qu'à trouver un second talk (work in progress).  
La salle est réservée, tu peux bloquer ta soirée ;)
