### ISSUE TITLE
Comment optimiser un code qui doit faire beaucoup de calculs

### ISSUE THREAD

**Issue by m-bouville** [ToulouseJug/call-for-paper#3]
## Sujet de votre conférence
Comment optimiser un code qui doit faire beaucoup de calculs

### Le speaker
Mathieu Bouville, PhD
consultant en conception et implémentation de modèles et algorithmes mathématiques

### Description de votre conférence
Les programmeurs savent comment améliorer la vitesse et la robustesse de leur code. Cependant, lorsqu'un programme fait beaucoup de calculs mathématiques, de nouveaux problèmes surgissent et de nouvelles solutions s'imposent pour obtenir des résultats rapides et précis. Le but de la présentation est de donner des principes généraux, pas des recettes sur comment implémenter tel ou tel calcul mathématique : http://mathieu.bouville.name/en/science/numerical-programming.html (en anglais) donne une idée de ce que je pourrais présenter.

### Informations diverses
* Thème, label : calculs mathématiques
* Niveau de difficulté (débutant|confirmé) : débutant/intermédiaire en programmation, bac S sans mention en maths
* Durée : 20-30 minutes
* Format (slides, live-coding, les deux) : slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): le 26 avril, puis en mai, juin, etc.

**Comment by arnaudbos** [comment]
Salut @m-bouville,
Ton sujet est resté en attente depuis un (long) moment, est-ce que tu serais toujours intéressé pour le donner en 2019 ?
