### ISSUE TITLE
Atelier OpenFaaS

### ISSUE THREAD

**Issue by Chabane** [ToulouseJug/call-for-paper#31]
## Sujet de la conférence 
Atelier OpenFaaS 🇬🇧

### Speakers/Coachs
  * [Alex Ellis](https://github.com/alexellis) (OpenFaaS founder)
  * [Laurent Grangeau](https://github.com/laurentgrangeau) (Sogeti)
  * [Olivier Dupre](https://github.com/OlivierDupre) (Sogeti)
  * [Philippe Charrière](https://github.com/k33g) (GitLab)

### Description de la conférence
Il s'agit d'un atelier OpenFaaS sur Kubernetes.

Langages au choix

Pré-requis:
Docker, Kubectl

### Informations diverses
* Niveau de difficulté : débutant, intermédiaire
* Durée : 3 heures - 19h-22h
* Format : slides + lab 
* Dispo : Septembre

**Comment by alexellis** [comment]
Oh, am I coming to this? 😄

**Comment by arnaudbos** [comment]
Can't say you didn't know anymore! :smile:

I honestly don't know if you were supposed to come or not; this landed on my radar but I didn't have a spot to schedule it just yet.  
Did someone get in touch with you about that?

**Comment by alexellis** [comment]
I should be free in September, just send the details over to me on email, my address is open on my profile. Sounds like a good event and I'd like to be a part of it if I can. 👍
