### ISSUE TITLE
Micronaut, le framework JVM ultra-light du futur

### ISSUE THREAD

**Issue by orevial** [ToulouseJug/call-for-paper#32]
### Le(s) speaker(s)

Olivier Revial, Développeur

### Description de votre conférence

Temps de démarrage proche de la seconde, empreinte mémoire de 10MB, pas de réflection, approche "cloud native" : autant de caractéristiques qui font du framework Micronaut le compagnon idéal  de développement de vos microservices Java/Kotlin.

Si des frameworks comme Spring Boot ont grandement facilité l'écriture d'applications en permettant de générer des applications standalone et auto-configurées, ils souffrent néanmoins de l'historique Spring et de sa "lourdeur". En effet, l'injection de dépendances au runtime et la réflection rendent plus longs les temps de démarrage et font grossir l'empreinte mémoire de nos applis.

En partant de 0, Micronaut prend le contre-pied de ses prédécesseurs en se passant de la réflection et en utilisant la "Ahead-Of-Time compilation" pour des temps de démarrage en dessous de la seconde !

Pensé de base pour supporter et faciliter le développement de microservices et d'applications serverless, Micronaut offre par défaut le support de nombreux providers et outils cloud, il permet l'écriture d'applications réactives, il rend les applications facilement testables... bref, il apporte tout ce dont on a besoin pour développer des applications modernes !

Cette présentation sera un live-coding pour montrer les principales fonctionnalités et les principaux points forts du framework Micronaut.

### Informations diverses

* Niveau de difficulté :  débutant
* Durée : 30 minutes
* Format : live-coding
* Dispo ou indispo : à partir d'avril

**Comment by swallez** [comment]
Talk fait le 4 avril 2019
