### ISSUE TITLE
Il ne faut pas vendre la peau de YARN parce qu'un Mesos vaut mieux que deux Kubernetes

### ISSUE THREAD

**Issue by pgillet** [ToulouseJug/call-for-paper#33]
Bonjour la Team du JUG Toulouse,

Je vous propose le sujet suivant:
"Il ne faut pas vendre la peau de YARN parce qu'un Mesos vaut mieux que deux Kubernetes"

# Speaker
Pascal GILLET
Big Data & Cloud Architect chez Stack Labs, Toulouse

# Elevator Pitch

Encore une présentation de Kubernetes !? Oui mais attendez...
Maintenant que la hype de K8s est (un peu) redescendue, il est l'heure de prendre un peu de hauteur et de placer le désormais célèbre framework de Google face à un écosystème bien en place avec notamment Mesos et YARN.

# Description

Bien que ces technologies permettent d'utiliser des conteneurs pour déployer, gérer et mettre à l'échelle des applications dans un cluster, elles résolvent en réalité des problèmes bien différents et sont ancrées dans des contextes très divers. En fait, aucun de ces outils largement adoptés n'est complètement comme les autres.

Plutôt que de [simplement] comparer les caractéristiques et les fonctionnalités qui se chevauchent de ces technologies en évolution rapide, revoyons la mission initiale de chaque projet, son architecture et la manière dont ces solutions peuvent se compléter et interagir les unes avec les autres.

On parlera d'ordonnancement et d'orchestration de conteneurs (avec Docker bien évidemment), d'allocation dynamique de ressources, et d'autres traits caractéristiques des gestionnaires de clusters. On évoquera également des _schedulers_ moins connus comme Nomad d'Hashicorp. Et nous nous risquerons à imaginer, pourquoi pas, notre solution idéale: hautement disponible, distribuée, capable de prendre en charge des services conteneurisés, virtualisés, _legacy_, de courte et longue durée... 

Ce Talk aborde des concepts d'informatique distribuée complexes. Pour cette raison, le niveau de ce Talk est fixé à "Intermédiaire". 
Il est aussi l'occasion de tenir un discours "engagé" et de nous rappeler à nous-mêmes, acteurs du monde numérique, consultants et salariés des ESN, que nous avons un devoir de conseil et que nous devons accompagner nos clients dans leurs choix techniques. Il faut pour cela nous informer sans cesse par de la veille technologique, comparer des solutions et en dresser un état de l'art, ne pas [tout de suite] céder à la hype des dernières technologies et développer un esprit critique.

À mon sens, il s'agit de rappeler ici la mission principale de l'architecte: être capable d'évaluer objectivement une ou plusieurs solutions selon des critères de coûts, fonctionnels et techniques.

# Notes

Le talk proposé a pour but d'expliquer les principes et les concepts derrière les systèmes d'orchestration de conteneurs, à savoir:
- Les stratégies d'allocation de ressources sur un cluster
- L'ordonnancement de tâches sur les noeuds de ce cluster
- Les contraintes de placement de tâches (règles d'affinité/anti-affinité)
- La découverte de services, le load balancing
- La scalabilité
- Les stratégies de déploiement et de mise à jour de services (blue/green, canary, rolling updates)
- Le health check & monitoring
- La Haute Disponibilité
- Les architectures master/agents

Ceci au travers des systèmes les plus connus:
- Hadoop YARN
- Mesos avec notamment Marathon pour l'orchestration de conteneurs Docker
- Kubernetes
- Nomad d'Hashicorp

Tout ceci sera expliqué en des termes d'architecture de haut niveau. Le format et le sujet de la présentation ne conviennent pas à une démo technique.
Le Talk se veut informatif bien sûr, mais également ludique et critique (pour les raisons invoquées plus haut).
Durée idéale: 1h

# Tags
#Architecture #Performance #DevOps/Cloud/Container & Scaling #French #Big Data

**Comment by arnaudbos** [comment]
Salut @pgillet 🙂 Je déterre les sujets pour un redémarrage du JUG :)
Est-ce que tu veux encore nous cause de ce sujet ? Ou de k8s ? Je crois qu'on n'a pas encore eu de talk sur ça.
Let me know!

**Comment by pgillet** [comment]
Hello @arnaudbos , tu déterres les sujets, effectivement!

Alors ce sujet est complètement obsolète. Et là, j'ai pas vraiment d'autres sujets sous le coude.
Mais je suis ravie que le JUG Toulouse reprenne du service, et je te ferai savoir si j'ai des idées intéressantes à présenter.

**Comment by arnaudbos** [comment]
👍 😄

**Comment by arnaudbos** [comment]
Fais passer le mot qu'on cherche des sujets autour de toi 😉
