### ISSUE TITLE
Débuter en GraphQL avec Spring

### ISSUE THREAD

**Issue by fbeaufume** [ToulouseJug/call-for-paper#34]
### Le(s) speaker(s)

Florian Beaufumé
Architecte logiciel et expert Java indépendant

### Description de votre conférence

GraphQL est une alternative à REST pour développer nos API web.

Conçu initialement par Facebook et désormais un standard, GraphQL a gagné en popularité grâce à ses avantages de performance et de maintenabilité.

Nous allons présenter les caractéristiques et le fonctionnement de GraphQL puis montrer sa mise en oeuvre dans une application Spring Boot.

### Informations diverses

* Niveau de difficulté :  intermédiaire
* Durée : 40 minutes
* Format : majorité de slides, un peu de live coding
* Dispo ou indispo : indispo

**Comment by arnaudbos** [comment]
Salut Florian, ça fait un petit moment que ton sujet est en standbye, est-ce que ça te dirais de revenir en janvier ?
Je pense que d'ici là on sera toujours en remote, mais si le confinement s'assoupli on pourra se poser la question présentiel ensemble.

**Comment by fbeaufume** [comment]
Salut Arnaud,

Je te remercie d'avoir pensé à moi. Je vais devoir décliner, trop de travail en ce moment pour trouver le temps de mettre à jour la présentation.

Je mets à jour ma dispo dans la description.

**Comment by arnaudbos** [comment]
Yes, c'est noté. Est-ce que tu veux qu'on prévois ça pour février du coup ?

**Comment by fbeaufume** [comment]
Plutot avril comme j'ai ajouté en haut.

**Comment by arnaudbos** [comment]
Ah, tu as écris "avril 2020", je pense que tu voulais plutôt dire 2021 de coup 😉 
Du coup on se recontacter vers fin janvier/début février, ok ?

**Comment by arnaudbos** [comment]
Salut Florian. On va essayer de reprendre du service, est-ce que tu voudrais toujours faire ce sujet dans les mois à venir ?

**Comment by fbeaufume** [comment]
Salut Arnaud. Content que le JUG reprenne.
Pour ce sujet c'est cuit, trop de temps s'est écoulé et la techno a évolué.
Je le passe à "indisponible".

**Comment by arnaudbos** [comment]
Et c'est bien compréhensible :-)
Si tu as d'autres sujets en vue, fais nous signe !
