### ISSUE TITLE
Développer des APIs Web Modernes avec GRPC

### ISSUE THREAD

**Issue by fb64** [ToulouseJug/call-for-paper#35]
### Le(s) speaker(s)

Florian Bernard
Architecte / Développeur logiciel 

### Description de votre conférence

La plupart des projets logiciels utilisent ou exposent des Api Web. Ces APIs sont souvent bâties sur des standards ( HTTP 1.X / JSON  / XML ….)  qui n’ont pas évolué depuis plusieurs années. Je vous propose de découvrir une approche plus moderne avec le framework [GRPC](https://grpc.io/) conçu par Google. 

Déroulement de la présentation : 
- Introduction et bref historique des technologies utilisées pour faire des Api distantes
- Présentation du framework GRPC et ce qu’il y a sous le capot
- Démo / live coding (client / serveur)

### Informations diverses

* Niveau de difficulté :  intermédiaire
* Durée : 40mn
* Format : slides + live-coding
* Dispo ou indispo : dispo à partir de juin 2019

**Comment by arnaudbos** [comment]
Salut Florian,
On cherche un speaker pour la soirée de rentrée le jeudi 5 septembre, est-ce que tu serais dispo ?

**Full-disclosure 1** : j'ai déjà proposé le rôle à @fbeaufume (avec #30) et tu es donc second sur la liste.
**Full-disclosure 2** : si Florian (l'autre donc) est disponible, je ne sais pas encore quand on planifiera ton talk, peut-être octobre ou novembre mais je ne peux rien te promettre.

En général j'essaie d'avoir 2 soirées d'avance mais je n'ai pas bien anticipé la rentrée.  
Désolé de te faire le coup du "plan B" :-)

**Comment by fb64** [comment]
Hello, si besoin je peux être dispo le jeudi 5 septembre. 
Pas de soucis si ça ne se fait pas ;-)

**Comment by arnaudbos** [comment]
Florian (l’autre donc) a confirmé qu’il serait disponible, du coup je vais
voir avec la team JUG quand on peut planifier ta présentation. En 2019 ça
me semble tout à fait faisable !

**Comment by fb64** [comment]
Ok, ça marche.

Le lun. 19 août 2019 à 20:50, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Salut Florian. Tu serais dispo le 10 octobre pour donner ton talk ?
La date n'est pas fixée mais ça semble le meilleur moment après le DevFest sachant que je ne serai pas dispo en début de semaine 41.

**Comment by fb64** [comment]
Hello, c'est bon pour moi pour le 10 octobre. Sachant que je vais au
devfest je pourrais aussi prendre 5mn pour faire un petit retour sur les
talks que j'ai vu à la fin de ma présentation.

Le mar. 10 sept. 2019 à 13:49, Arnaud Bos <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Impec, je t'ajoute au milestone et je vais annoncer ça :-)
