### ISSUE TITLE
Java + Blockchain + Open Source = Pegasys

### ISSUE THREAD

**Issue by faraggi** [ToulouseJug/call-for-paper#38]
### Le speaker
Felipe Faraggi: développeur et 'Developer Evangelist' pour [Pegasys](pegasys.tech), projet blockchain open source basé sur la techno de ethereum **et écrit en Java**.

Expériences de présentation: Multiples presentations internationales de blockchain et ethereum (Madrid, Toulouse, Paris, Cancun, Ljubiana, etc) + sujets de Decentralized Applications (dapps) 
 + autres...

### Description de votre conférence

Cette presentation a pour but de introduire le concept de blockchain et leur logiciels pour ensuite discuter en detail sur l'implementation du client en Java: [Pantheon de Pegasys](https://github.com/PegaSysEng/pantheon). La presentation est interactif et elle fini avec une demonstration et la creation d'une blockchain privé en live.

Contenus:  
* Introduction des concepts de blockchain et Ethereum
* Introduction des concepts de Eth2.0
* Overview des clients ethereum actuels; Geth, Parity, cpp-ethereum, pyethapp, EWasm
* Detail du logiciel Pantheon et ça importance dans l'écosystème blockchain/ethereum
* Installation et demo du logiciel Pantheon
* Q&A

### Informations diverses

Thème : blockchain, ethereum
Niveau de difficulté : débutant et confirmé
Durée : 45-60 mins
Format : slides + démo
Dispo : à partir du 15 mai 2019

**Comment by faraggi** [comment]
Bonjour, est-ce que cet talk intéresse quelqu'un?

**Comment by arnaudbos** [comment]
Salut. Dans l'absolu oui, mais le planning de juin et septembre est pris et il y a en a d'autres dans la liste qui ont plus de votes, donc on ne vas pas le programmer dans l'immédiat.  
Si tu veux spécifier un TTL n'hésite pas à la rajouter dans la partie "Dispo".

**Comment by faraggi** [comment]
> Salut. Dans l'absolu oui, mais le planning de juin et septembre est pris et il y a en a d'autres dans la liste qui ont plus de votes, donc on ne vas pas le programmer dans l'immédiat.

Aucun soucis pour planifier ça pour plus tard, je ne suis pas pressé- je voulais juste savoir si cet 'issue' a était oublié.  merci pour ta réponse.
