### ISSUE TITLE
La concurrence sans s’emmêler les ficelles avec Project Loom

### ISSUE THREAD

**Issue by arnaudbos** [ToulouseJug/call-for-paper#39]
### Le(s) speaker(s)

Arnaud Bos. I like hammocks and Clojure.

### Description de votre conférence

Le domaine de la programmation concurrente utilise le champ lexical de la filature et nous met les nerfs en pelote avec des concepts qui s'entrelacent : fibers, threads, lightweight-threads, green threads, loom...  
Peut-être avez vous également entendu parler de coroutines ? Rassurez-vous, tout est lié.

Au fil de cette présentation (em)mêlée d'exemples de code, vous découvrirez le projet Loom qui a pour vocation d'apporter à la JVM des "mécanismes léger de concurrence", ainsi que des API plus haut niveau pour broder dessus.

Nous aborderons ensemble l'origine de Loom et ses récents prototypes. Vous vous apercevrez que son maillage va au delà de "simples" primitives et peut nous amener jusqu'à révolutionner la concurrence sur la JVM.

Et en attendant la révolution, sans tirer trop sur la corde, vous verrez comment on peut juste utiliser Quasar.

### Informations diverses

* Niveau de difficulté :  intermédiaire ?
* Durée : 50mn
* Format : slides
* Dispo ou indispo : avant octobre (pour préparer Voxxed Days Ticino)

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux banir, les trolls durant ma présentation

**Comment by fcabestre** [comment]
Owi, j'en veux de cette présentation !
