### ISSUE TITLE
Retour sur DevoxxUS

### ISSUE THREAD

**Issue by mbats** [ToulouseJug/call-for-paper#4]
## Sujet de votre conférence
Retour sur DevoxxUS

### Le(s) speaker(s)
BATS Mélanie, Software developer chez Obeo, Eclipse Committer.

### Description de votre conférence
Un nouveau petit Devoxx, la conférence pour les développeurs par les développeurs,  est naît loin loin de ses petits frères par delà l'océan: DevoxxUS qui a eu lieu du 21 au 24 mars à San Jose Californie. 
Ayant eu la chance d'y participer, le but est de partager avec vous tout ce que en tant que développeuse Java, j'ai aimé, détesté et tout ce que j'ai pu y découvrir. Cette présentation sera donc un rapide tour d'horizon des différentes thématiques qui ont été abordées afin de vous donner des liens que vous pourrez creuser à la maison.

J'ai déjà fait cette présentation lors de l'Eclipse Democamp de Nantes : https://www.meetup.com/fr-FR/Communaute-Eclipse-Nantes/events/238024071/
Les slides sont disponibles sur slideshare : https://www.slideshare.net/melbats/eclipse-democamp-nantes-2017-back-to-the-future-eclipseconverge-devoxx-us

### Informations diverses
* Thème, label : Devoxx US
* Niveau de difficulté (débutant|confirmé) : débutant
* Durée : ~25 min
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dès que possible

**Comment by davinkevin** [comment]
Encore d'actualité de ton point de vue ? 

De mon point de vue, cela ne vaut plus le coup de le faire maintenant... hésite pas à nous dire 😉

**Comment by mbats** [comment]
Ha bin non là ça vaut plus le coup c'est sûre :)

**Comment by davinkevin** [comment]
Ok.

La fin de saison a été super chargé l'année dernière... 

Je clôture. Merci pour ta proposition tout de même !

PS: pour les sujets type "débrief", hésite pas à les proposer avant les évènements pour qu'on les cale au plus proche après l'évènement...
