### ISSUE TITLE
L'accessibilité: pour qui, pourquoi, comment ?

### ISSUE THREAD

**Issue by icidel** [ToulouseJug/call-for-paper#41]
### Le(s) speaker(s)

Laurent Asfaux. Développeur Java/J2EE/Eclipse RCP, désormais employé à la qualification des performances applicatives.

### Description de votre conférence

Cette présentation de l'accessibilité se veut la plus exhaustive possible au travers de trois parties de plus en plus détaillées :

1. pour qui ?
Présentation du public visé par l'accessibilité et des formes d'accessibilité.
2. pourquoi ?
Identification des textes de loi et directives européennes pour l'accessibilité numérique. Information sur les normes relatives à l'accessibilité numérique (WCAG, VPAT).
3. comment ?
Détail des outils pour tester l'accessibilité d'une application ou d'un site web:
- Multiplateforme / Web : Java access bridge, IAccessible2
- Documents : PDF, Word, mais aussi de type image, vidéo ou audio
- Windows : Microsofy active accessibility (MSAA)
- Linux : Accessibility API (GNOME), ATK
- Mac : Mac Accessibility API

Nous verrons que ces outils ont de nombreux points communs sur la manière de rendre une informations accessible aux personnes handicapées.

### Informations diverses

* Niveau de difficulté :  intermédiaire
* Durée : 1h
* Format : slides
* Dispo ou indispo : après Octobre

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux banir, les trolls durant ma présentation

**Comment by arnaudbos** [comment]
Je ferme car "trop vieux" à priori. N'hésite pas à rouvrir si c'est toujours d'actualité.
