### ISSUE TITLE
Architecture Hexagonale, retour d'expérience

### ISSUE THREAD

**Issue by Marthym** [ToulouseJug/call-for-paper#44]
### Le(s) speaker(s)

Frédéric Combes
CTO chez BOTdesign

### Description de votre conférence

On a pas mal parlé d’architecture hexagonale dans les conférences des dernières années. Mais qu'est-ce que ça donne en vrai quand on essaye de le mettre en place dans une équipe de développeurs de tous niveaux ?

* Rapide tour de ce qu'est l'architecture hexagonale et des problèmes qu'elle tente de résoudre. 
* Contexte et raison de la mise ne place de ce type d'architecture chez i-Run.fr
* Mise en place
* Retour d'expérience
  * Ce qui a bien marché
  * Ce qui a été difficile

### Informations diverses

* Niveau de difficulté :  débutant
* Durée : 35~40 mn
* Format : slides
* Dispo ou indispo : dès que possible && pas entre 28 mars 2020 et 22 avril 2020

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by jzanon** [comment]
Oui !
On cale ça pour la rentrée

**Comment by arnaudbos** [comment]
La rentrée a été décalée aussi 😅
Ok pour le 16/02 ou 07/03 si je trouve une salle @Marthym ?

**Comment by Marthym** [comment]
Bonjour @arnaudbos 
Ca m'arrange plus de **07 mars** si c'est bon pour vous. Mais si besoin je peux faire le 16 février aussi.

**Comment by arnaudbos** [comment]
Pas besoin de se stresser 🙂 J'essaye de trouver une salle pour le 07/03 et je te tiens au courant !

**Comment by arnaudbos** [comment]
On a le Livepoint pour le 07/03 ! C'est bon pour toi je peux lancer la com' ?

**Comment by Marthym** [comment]
Yes super !
