### ISSUE TITLE
Let the compiler work for you...

### ISSUE THREAD

**Issue by enhan** [ToulouseJug/call-for-paper#46]
### Le(s) speaker(s)

Emmanuel Nhan, backend developer at Linkfluence.

### Description de votre conférence

Ça bouge du côté de Scala. La version 3 du langage, après des années de travail sous le nom de Dotty, devient chaque jour plus proche du grand public. Avec la release de [Dotty](http://dotty.epfl.ch/) 0.22.0-RC1 , on commence à atteindre un compiler et un langage qui ont repoussé au loin les contraintes de Scala 2. 
Dans ce talk, on verra quelques nouvelles fonctionnalités du langage qui permettent au développeur de s'amuser avec les types et de laisser le compilateur travailler pour lui. En particulier, on s'intéressera à utiliser le système de types comme spécification très précise.

*Note : à minima, on parlera du nouveau type `enum`, de Singleton types,  des extension functions et de type lambdas*

### Informations diverses

* Niveau de difficulté :  intermédiaire *(contenu à peaufiner encore)*
* Durée : 40min 
* Format : slides + un peu de live code *(contenu à peaufiner)*
* Dispo ou indispo : à partir de début mai 2020

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by enhan** [comment]
Peut-être doublon avec https://github.com/ToulouseJug/call-for-paper/issues/43 ?

**Comment by arnaudbos** [comment]
Très probablement, mais @adpi2 va quitter Toulouse très bientôt, si j'ai bien compris :-)

**Comment by arnaudbos** [comment]
Salut @enhan 👋 Est-ce que tu veux encore parler de Scala lors d'une future soirée du JUG ?

**Comment by enhan** [comment]
Salut @arnaudbos ! yes, pourquoi pas. Bon, j'ai rien en stock par contre. Je pense que tu peux fermer cette issue. Je vais réfléchir à tout ça et proposer un autre sujet.

**Comment by arnaudbos** [comment]
Ça marche !
