### ISSUE TITLE
Distributed Systems, a journey through data consistency

### ISSUE THREAD

**Issue by TheoCadoret** [ToulouseJug/call-for-paper#47]
### Le(s) speaker(s)

Théo Cadoret, curieux de systèmes distribués chez Stack-Labs.

### Description de votre conférence

Gérer un utilisateur accédant à une seule ressource sur une base de donnée est *trivial*.  
Mais vous n'irez jamais très loin.

Gérer un utilisateur accédant à **plusieurs ressources** sur une base de donnée est assez *facile*.  
Mais vous vous sentirez vite seul(e).

Gérer **plusieurs utilisateurs** accédant à **plusieurs ressources** sur une base de donnée est *difficile*.  
Mais que se passe-t-il si votre base de données tombe ? 

Gérer **plusieurs utilisateurs** accédant à **plusieurs ressources** sur une **base de donnée distribuée** est vrai *cauchemar*.  
Mais est-ce que c'est ce que vous voulez vraiment finalement ? 

Des termes tels que Linearizability, Transactions, Serializability, Snapshot Isolation, Consensus, Replication, Sharding, Read committed, Two phase commit, quorum, Causal consistency, availability etc sont un peu nébuleux ? Leur relation est floue ?

Nous aborderons tous ces concepts à travers la croissance d'un petit logiciel qui sera amené à faire face à plus de problèmes que prévu..

### Informations diverses

* Niveau de difficulté :  Débutant-ish
* Durée : 45' ish
* Format : slides
* Dispo ou indispo : A partir d'avril j'dirais

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by arnaudbos** [comment]
@TheoCadoret je close vu que ça a 4 ans... Rouvre le si besoin 🙂
