### ISSUE TITLE
Randomness, what did you expect ?

### ISSUE THREAD

**Issue by TheoCadoret** [ToulouseJug/call-for-paper#48]
### Le(s) speaker(s)

Théo Cadoret, just me. 

### Description de votre conférence

Despite being inherently unreachable to softwares, Randomness is yet widely used.

What is Randomness ?   
Why is it so vital to softwares ?   
How do we cope with this apparent paradox ?

Let's got for a quick dive in !

Lien des slides : https://docs.google.com/presentation/d/e/2PACX-1vQm87hbEiuYGbkO2VZCrZXKQFEQwy3MFY8NHBx8ykEkNXvdNVzQvTa2l9xi852HBFtQFFxXrCOBcHaf/pub?start=false&loop=true&delayms=60000&slide=id.g8832cf8d8e_0_104

### Informations diverses

* Niveau de difficulté :  Débutant
* Durée : ~20mn
* Format : slides 
* Dispo ou indispo : Globalement dispo hein.

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by arnaudbos** [comment]
Yo l’ami !
On pense à toi pour la prochaine soirée (remote 😷), manière de faire la rentrée !
T’as deux talks dans le CfP en ce moment. L’autre y est depuis plus longtemps mais avec @jzanon on te propose de présenter celui-ci en premier (si l’autre te tiens plus à ❤️ ça se discute hein !).
Ça te tente ? On pensait au 22/10 là comme ça.

**Comment by TheoCadoret** [comment]
Hello !
Très bien de commencer par celui-là, l'autre n'a pas encore été beta testé. Et puis 20mn sur du Random c'est plus facile qu'1h de systèmes distribués pour mettre le pied à l'étriller !
22/10 parfait de mon côté.

**Comment by arnaudbos** [comment]
T'es programmé !

**Comment by TheoCadoret** [comment]
Top 🤩
