### ISSUE TITLE
Programmation réactive avec Spring 5 et Reactor

### ISSUE THREAD

**Issue by fbeaufume** [ToulouseJug/call-for-paper#5]
## Sujet de votre conférence

Programmation réactive avec Spring 5 et Reactor

### Le(s) speaker(s)

Florian Beaufumé est un architecte logiciel spécialisé en Java de 19 ans d'expérience. Consultant indépendant depuis 2007, il a travaillé pour des grands comptes, des éditeurs de logiciels, des SSII et des startups dans les domaines tels que les banques, les assurances et l'aéronautique.

### Description de votre conférence

Pour des microservices ou pas, la programmation réactive on en entend beaucoup parler, mais elle peut paraître abstraite. Avec son support dans Spring 5 une étape est franchie et c’est l’occasion de s’y intéresser de près !

Nous allons introduire concrètement la programmation réactive et ses bénéfices, puis sa mise en oeuvre concrète avec Spring 5 et la librairie Reactor, mais aussi expliquer ses limitations.

### Informations diverses

* Thème, label : programmation réactive, spring, reactor
* Niveau de difficulté (débutant|confirmé) : confirmé
* Durée : 45 minutes
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): à partir d'octobre 2017

**Comment by fbeaufume** [comment]
Je termine l'écriture de la présentation. Je serai prêt pour le mois prochain, octobre 2017.

Y'a plus qu'à lancer la rentrée 2017 du JUG !

**Comment by davinkevin** [comment]
Ok pour moi, à voir si un autre sujet est prêt ;) (et il me semble que oui...)

Et il faut trouver une date...

**Comment by fbeaufume** [comment]
Mis à jour la description : la présentation sera avec slides mais aussi live coding.

**Comment by davinkevin** [comment]
Tu serait prêt pour le 9 Novembre ? 

Cela permettrait de faire une soirée avec #6

**Comment by fbeaufume** [comment]
Oui c'est bon pour moi.

**Comment by fbeaufume** [comment]
Salut Kevin,

Oui c'est bon pour moi.

**Comment by davinkevin** [comment]
Hello @fbeaufume , dans le cas de la captation, tu as pas changé de machine/OS depuis la dernière fois ? Pas la peine normalement de refaire les tests normalement ?

**Comment by fbeaufume** [comment]
Salut, oui sauf surprise je viendrai avec la même machine.

**Comment by davinkevin** [comment]
Parfait, merci ;)
