### ISSUE TITLE
X Exemples de Cloud functions que vous pouvez intégrer facilement à vos projets - Guilhem de Miollis

### ISSUE THREAD

**Issue by gdemiollis** [ToulouseJug/call-for-paper#50]
## Le speaker
Guilhem de Miollis
Freelance Cloud

* Twitter handle:

## Sujet de votre conférence
X Exemples de Cloud functions que vous pouvez intégrer facilement à vos projets

## Description de votre conférence
Dans ce talk, nous allons explorer les capacités des Google Cloud functions sur des vrais cas en production.
Nous allons voir :
 - Comment mixer différents langages au sein d'un même SI afin de profiter des avantages de chacun d'eux (La majorité des exemples seront en python)
 - Les différents déclencheurs : requête http, pubsub, CRUD firestore, ajout de fichier dans cloud storage
 - Les fonction librairies intégrées nativement (Traitement d'images)
 - Les interactions possibles avec d'autres API (Envoie de mail, SMS, Vision, etc...)
 - Les Firebase extensions qui sont cloud functions déjà codée à intégrer directement dans votre projet Firebase
 - Comment organiser ces Cloud functions afin de mutualiser du code et ne déployer que celles concernées par les changements

## Informations diverses
* Thématique, Labels : iOT, Cloud, Tooling
* Niveau de difficulté (débutant|avancé|confirmé) : Avancé : Une connaissance du Cloud peut être utile.
* Durée (max 45 min) : 30 min
* Format (slides, live-coding, les deux):  Slides
* Dispo : ASAP

**Comment by gdemiollis** [comment]
Salut Arnaud,

Oui ça pourrait le faire pour fin mai. Je n’ai encore rien commencé,
j’attendais de voir si du monde était intéressé avant de commencer la
présentation.

Dis-moi si t’as besoin d’aide pour le lieu, je peux te présenter chez
Harrycow si besoin.

Guilhem

Le mar. 12 avr. 2022 à 10:26, Arnaud Bos ***@***.***> a
écrit :

**Comment by arnaudbos** [comment]
En général on fait les soirées en début de mois, mais de toute façon pour mai c'est compromis. Entre les vacances scolaires et le temps qu'on a mis à redémarrer le JUG, c'est foutu.

Est-ce que début juin ce serai possible pour toi ? On vise le 9 ou le 14, à confirmer, "**évidemment**" :)

**Comment by gdemiollis** [comment]
Salut Arnaud,

Désolé de te répondre si tard, mais je viens de commencer une nouvelle
mission et j'ai encore quelques heures à faire sur la précédente, donc
c'est un peu tendu. Je pense que ça va être compliqué pour la faire en
juin, surtout qu'avec les ponts et le beau temps, je vais recommencer à
bouger sur des grands week-end.

Est-ce que si on se dit pour la rentrée, ça te va?

Encore désolé

Guilhem

**Comment by arnaudbos** [comment]
Pas de soucis, je te déprogramme du 14.

À plus.
