### ISSUE TITLE
SELECT 'amazing_features' FROM "postgresql"

### ISSUE THREAD

**Issue by davinkevin** [ToulouseJug/call-for-paper#51]
### Le(s) speaker(s)

DAVIN Kevin, Senior Software Backend Engineer chez Gradle

#### Bio

> Google Developer Expert on Google Cloud & Kotlin, Gitlab Hero, I am above all passionate about tech, languages, infrastructure, and automation.
> 
> On a daily basis, I work with languages such as Kotlin, Java, SQL, and YAML.
> Leveraging the power of the Google Kubernetes Engine and GitLab's Continuous Integration, I deploy and manage applications seamlessly.
> 
> I am an ardent advocate of agility and DevOps, and I have had the privilege of guiding teams in adopting these principles successfully.
> 
> From code quality analysis to unit or end-to-end tests setup all the way to continuous deployment and operation, I ensure a project's journey from inception to production is smooth and efficient.
> 
> Currently, I serve as a Software Engineer at Gradle, focusing on the development of Gradle Enterprise. This groundbreaking product enhances developer productivity by reducing build and test times, while also providing valuable insights into all aspects of the development process."

#### Ref 2023

  * JOOQ, Joy of SQL
    * [BordeauxJUG Feb 2023](https://twitter.com/BordeauxJUG/status/1627560496617357316)  | [Slides](https://link.davinkevin.fr/jooq-bordeauxjug-slides)
    * [LyonJUG March 2023](https://www.meetup.com/fr-FR/lyonjug/events/291758933/)  | [Slides](https://link.davinkevin.fr/jooq-lyonjug-slides)
    * [Riviera Dev 2023](https://link.davinkevin.fr/jooq-riviera23-program)  | [Slides](https://link.davinkevin.fr/jooq-riviera23-slides)
  * SELECT 'amazing_features' FROM "postgresql"
    * [DevoxxFR 2023](https://cfp.devoxx.fr/2023/talk/OFK-3682/SELECT_'amazing_features'_FROM_%22postgresql%22) | [Replay](https://link.davinkevin.fr/amazing-pg-devoxxfr23-video) | [Slides](https://link.davinkevin.fr/amazing-pg-devoxxfr23-slides)
    * [Sunny Tech 2023](https://sunny-tech.io/sessions/select-amazingfeatures-from-po) | [Replay](https://link.davinkevin.fr/amazing-pg-sunnytech23-video) | [Slides](https://link.davinkevin.fr/amazing-pg-sunnytech23-slides)
    * [Riviera Dev 2023](https://link.davinkevin.fr/amazing-pg-riviera23-program)  | [Slides](https://link.davinkevin.fr/amazing-pg-riviera23-slides)
  * Let's kustomize our manifests with style 🤩!
    * [Tech a break #2](https://www.meetup.com/fr-FR/tech-a-break/events/291683371/)  | [Slides](https://link.davinkevin.fr/kustomize-techabreak-slide)
    * [Sunny Tech 2023](https://link.davinkevin.fr/kustomize-sunnytech23-program) | [Replay](https://link.davinkevin.fr/kustomize-sunnytech23-video) | [Slides](https://link.davinkevin.fr/kustomize-sunnytech23-slides)
  * Et vous votre(vos) fonctionnalité(s) GitLab préférée en 2022 ... Et 2023 ?
    * [DevoxxFR 2023](https://cfp.devoxx.fr/2023/talk/QXB-1177/Et_vous_votre(vos)_fonctionnalite(s)_GitLab_preferee_en_2022_..._Et_2023_%3F)  | [Slides](https://docs.google.com/presentation/d/10W3kMEgIIJ_Rff6VnyKpkxSp0rRRKdPVGMPjQJPdIxs/edit?usp=share_link)

### Description de votre conférence

C'est unanime, `PostgreSQL` devient le Linux de la base de données pour le bien de tous 🚀!
Et cela parce que ce moteur de BDD contient des fonctionnalités fantastiques permettant de résoudre des problèmes complexes très simplement!

<img src="https://link.davinkevin.fr/pgfeatures-cover" alt="drawing" width="200"/>

Venez découvrir dans cette présentation les features les plus utiles et pratiques pour vous éviter de tout re-coder "from scratch" 😅!
L'on détaillera des features standards du monde SQL trop peu connues et des features propres à PG qui en font un moteur SQL passionnant 🔥

Et pour terminer, l'on fera le tour des "distributions" `PostgreSQL` disponibles, car dans ce domaine, il y a beaucoup de choix, pour de l'on-prem ou dans le cloud ☁️

Les slides et replays sont disponibles dans mes ref ci dessus. 

### Informations diverses

* Niveau de difficulté :  débutant
* Durée : 45mins minimum
* Format : slides contenant beaucoup de code…
* Dispo : Pas dispo durant la semaine 43. Hors de cela, pas de contrainte forte.

### Règles de courtoisie

- [X] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [X] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by arnaudbos** [comment]
@davinkevin tu déchires ! On cherchait justement un sujet pour septembre, hein @jzanon ? 😄

**Comment by davinkevin** [comment]
Si je peux rendre service 😇, et il faut aussi rendre aux JUG(s) un peu, il n'y a pas que les confs dans la vie! ♥️

Septembre, pas de contrainte en vue, donc cool pour moi 👍. N'hésitez pas à me dire dès que vous avez une date probable.

**Comment by davinkevin** [comment]
@arnaudbos, Septembre est terminé, des news sur le sujet?

**Comment by arnaudbos** [comment]
Hello @davinkevin, désolé je suis entre deux mission, c'était un peu chaud à organiser et j'ai laissé passer septembre, mais merci pour le ping !

Je vais avoir du temps pour gérer ça semaine prochaine si ça te dérange pas d'attendre quelques jours de plus ?

**Comment by davinkevin** [comment]
No pb, j'ai juste quelques indispos qui se placent en + de la semaine 43. Je ne vais pas être dispo le 12 et 13 Octobre non plus.

Étant déjà le 4, cela diminue un peu les possibilité pour Octobre si l'on veut communiquer sur l'event. 

À toi de me dire! Bon déménagement et merci encore pour l'invit' 😇

**Comment by arnaudbos** [comment]
Hello @davinkevin, je ne t'ai pas oublié mais j'ai été complètement débordé, c'est évidemment inexcusable 😄 

J'essaye de renouer des contacts avec d'anciens et nouveaux lieux d'hébergement mais c'est pas la panacée.

Est-ce que tu as de la dispo début janvier ? Genre mardi 9 ou 16 ? D'ici là je me débrouillerai pour le lieu, parce que si j'attends que les planètes s'alignent d'elle mêmes il ne se passera jamais rien !

**Comment by davinkevin** [comment]
Hello @arnaudbos, 

Une pref pour le 9, car la semaine suivante j'ai un conf le Jeudi/Vendredi, donc j'aimerai éviter trop de chose la même semaine. 

Ne t'inquiète pas du tout, je reste "dispo" pour le JUG, je connais cette position et en aucun cas je dirai que cela n'est pas excusable ♥️. 

Thx

**Comment by arnaudbos** [comment]
On part sur le 9 alors, save the date 🎉 

De mon côté je relance la machine "comm" et je nous trouve un lieu !

**Comment by davinkevin** [comment]
Hello 👋 et bonne année 🎉, 

À peine une semaine avant l'event, je pense que cela va être trop court de nouveau pour la com' et le reste, non? 

Toujours dispo de mon côté, j'aurai surtout des contraintes de planning avec les futures conf (VoxxedDays Lugano, Snowcamp…) et des contraintes pro/perso. Si changement de date il y a, n'hésite pas à me pinguer ici ou ailleurs et je me ferai un plaisir de trouver un slot pour participer à mon JUG favoris ♥️

**Comment by arnaudbos** [comment]
J'attends encore le go pour l'hébergeur mais avec les congés de fin d'année c'est compliqué.

Dans l'absolu c'est pas mort pour la comm' mais pour le lieu c'est chaud, si j'ai pas de news d'ici ce soir il va sûrement falloir reprogrammer :/

Je te dis ça demain.

**Comment by arnaudbos** [comment]
J'attends toujours le "go" donc en effet là c'est vraiment foutu pour le 9 ^^

VoxxedDays Lugano c'est le 19 et SnowCamp le 31 si je ne me trompe pas. Si tu tiens la forme on peut se tenter le 23 ou le 25, mais si tu veux souffler un peu on peut reprogrammer pour février :)

**Comment by davinkevin** [comment]
23 jouable… cela serait sportif mais possible 😇. 
Sinon Fév sans problème, je n'ai pas de conf prévue… et comme je n'ai postulé à rien, peu de risque de surprise 😇. 

Je te laisse choisir en fonction du lieu et des dispo de tout le monde et de la com' à faire. 

Cependant, suis-je le seul talk prévu pour cette soirée?

**Comment by arnaudbos** [comment]
Oui, on est en période de famine question sujets/speakers en ce moment. J'ai pas vraiment pris le temps d'analyser ça mais je pense que c'est un combinaison de manque de visibilité/attractivité après le hiatus post-covid et du tag "java" sur l'étiquette. Mais difficile de relancer la machine sans sujets.

Si tu veux partager ton carnet d'adresse tu as mon mail 😛

**Comment by arnaudbos** [comment]
PS: je vais faire des relances pour trouver un lieu pour le 23, si j'ai pas de réponses le 10 on reporte à février.

**Comment by davinkevin** [comment]
LGTM, sauf que l'on a pas de second speaker 😓…

**Comment by davinkevin** [comment]
Au pire, j'ai le talk jooq, thème proche mais différent. Cela permet d'avoir deux talks. Je l'avais fait au jug en période COVID, en remote, donc on avait pas d'audience folle à cette époque. 

Sinon, tu en aurais pas un en stock? Ou via un Monkey?

**Comment by arnaudbos** [comment]
J’y avais pas pensé mais je peux reprendre mon talk sur TLA+ que j’ai fait
au DevFest il y a quelques semaines. J’avais prévu de le retravailler, ça
peut être l’occasion. Je pense pouvoir faire une transition depuis
PostgreSQL d’ailleurs si je passe en second.

Le mar. 9 janv. 2024 à 20:54, Davin Kevin ***@***.***> a
écrit :

**Comment by davinkevin** [comment]
Toujours ok? On est à une semaine-ish de l'event et je ne voie pas l'évent sur [Meetup](https://www.meetup.com/fr-FR/toulouse-java-user-group/events/).

**Comment by arnaudbos** [comment]
C'est parce que tu ne peux pas voir les brouillons :-)
J'attendais ce midi dernier délai pour trouver une second speaker et c'est chose faite.
J'ai créé l'event sur meetup en brouillon ce midi, ça part ce soir.

--
Arnaud Bos
Software Developer @MonkeyPatch_io
@ToulouseJUG Leader
+33 6 51 23 41 07

**Comment by davinkevin** [comment]
Cool! Rassuré ♥️. 

PS: je peux le voir (encore admin dessus je pense)… mais je n'ai pas pensé à cliqué sur brouillon 😅

**Comment by arnaudbos** [comment]
Il me semblait bien que t'avais encore les droits mais j'ai pas voulu présumer ^^

T'inquiète c'est sur la rampe de lancement !

--
Arnaud Bos
Software Developer @MonkeyPatch_io
@ToulouseJUG Leader
+33 6 51 23 41 07

**Comment by davinkevin** [comment]
Ready pour demain?! 🔥

Deux questions, est-ce que je passe en second comme semble l'indiquer le [titre du meetup](https://www.meetup.com/fr-FR/toulouse-java-user-group/events/298562945/) (ce qui ne me gêne pas du tout) et combien de temps ai-je pour la prez? (souvent les JUG étant moins regardant sur la durée, je peux être un peu plus "relax" 😅).

**Comment by arnaudbos** [comment]
🎉 

J'ai préféré te faire passer en second parce que je ne connais pas l'expérience (en tant que speaker) du premier intervenant, et j'ai jugé préférable de ne pas le laisser stresser pendant toute la durée de ton talk, alors que toi je me suis dit que tu pouvais endurer 😆 

La durée de son talk sera probablement un peu plus courte que la tienne, je table sur 30-40mn, ça te laisse 45-55mn max pour ne pas trop déborder sur l'apéro parce qu'exceptionnellement on aura un couvre-feu à 22h30. Après comme tu l'as dit c'est plus chill au JUG donc pour peu que je lance les ostilités à l'heure, on devrait quand même être assez large 🙂

**Comment by davinkevin** [comment]
Parfait, no problème pour etre second, très bonne raison, merci pour lui! 

Cool pour mon timing, je pourrais un peu plus dérouler et je prendrai les questions en apéro 🤩

À demain
