### ISSUE TITLE
Développer un dispositif médical

### ISSUE THREAD

**Issue by Marthym** [ToulouseJug/call-for-paper#53]
### Le(s) speaker(s)

COMBES Frédéric, CTO chez BOTdesign

### Description de votre conférence

Il y a beaucoup de travail à faire dans la santé pour fournir aux professionnels les outils de demain. Mais qu'est-ce que cela veut dire travailler dans la santé ?
Qu'est ce qu'un dispositif médical ? A quoi cela sert ?

Dans cette présentation je vous propose de découvrir un peu le monde du logiciel en santé et ce qu'est un dipositif médical, comment cela se met en place et l'impact que cela a sur le métier de développeur.
Quels sont les avantages et les inconvénients de travailler sur ce genre de logiciel au quotidien.

### Informations diverses

* Niveau de difficulté : débutant
* Durée : 30mn
* Format : slides
* Dispo ou indispo : Prévenir au moins un mois à l'avance si possible.

### Règles de courtoisie

- [x] J'ai lu le [Code of Conduct du JUG](http://www.toulousejug.org/page/coc/), j'en comprends la teneur et je m'engage à le respecter
- [x] Je suis sensibilisé au fait que [la limite entre troll et mépris est ténue](https://blog.aurynn.com/2015/12/16-contempt-culture) et m'engage à limiter, ou mieux bannir, les trolls durant ma présentation

**Comment by arnaudbos** [comment]
Salut Fred, on n'avait pas eu le temps de rediscuter de ton sujet et puis j'ai vu que tu l'avais clôturé.

Tu n'es plus intéressé pour donner ce talk ? Parce que j'ai un peu trop traîné peut-être ?

Je vois qu'il y a un sujet IoT/CoAP d'ouvert dans le Cfp, je me demandais si ça pouvait vaguement être relié pour faire le thème d'une soirée, ou pas :)

**Comment by Marthym** [comment]
Salut,

Non non, pas que tu ai trop trainé du tout, c'est plus moi qui suis plus trop inspiré pour traiter ce sujet, c'est pour ça que je l'avais fermé. Après, pas sur que ça aurait peu faire un thème avec IoT/CoAP

**Comment by arnaudbos** [comment]
Bien noté merci beaucoup pour les explications ! 🙂
