### ISSUE TITLE
Le meilleur langage de programmation jamais conçu: Lisp sur la JVM

### ISSUE THREAD

**Issue by arnaudbos** [ToulouseJug/call-for-paper#6]
## Sujet de votre conférence

Le meilleur langage de programmation jamais conçu: Lisp sur la JVM

### Le speaker

Arnuad Bos. Passionné par les langages de programmation, les parenthèses et les systèmes distribués. Wannabe Data Engineer, mon expertise se concentre sur le développment backend (Clojure, Python, Java) et Web (React, Angular). Amateur de hamacs et de petites startups où l’on peut s’engager.

### Description de votre conférence

“The greatest single programming language ever designed.” - [Alan Kay](https://en.wikipedia.org/wiki/Alan_Kay), about Lisp.

Clojure est un langage fonctionnel pour la JVM inspiré du plus ancien langage de programmation fonctionnel: Lisp.
En bon héritier, Clojure expose un style de programmation dynamique (REPL) basé sur des fonctions “as first-class citizens”, l’immutabilité et des structures de données persistantes.
Ses puissantes abstractions sur les collections et le polymorphisme ainsi que ses modes de gestion de la concurrence en font un langage adapté à tous types d’applications.

Profitez des 10 ans de Clojure pour découvrir sa philosophie de séparation entre identité et état ainsi que sa librairie standard, tout en profitant de l’écosystème Java.

### Informations diverses

* Thème, label : Clojure, Programmation fonctionnelle
* Niveau de difficulté : débutant
* Durée : ~50mn
* Format : Slides & live-coding
* Dispo: Début Octobre 2017, avant la Toussaint.

**Comment by ilaborie** [comment]
👍

**Comment by nicolas-zozol** [comment]
👍  mais je préfère Javascript, au moins ça tourne le navigateur.
Traditionnellement, c'est le 3e jeudi du mois, donc je propose le jeudi 19 octobre. Les vacances tombent le 21 et traditionnellement toujours, on ne fait pas de Jug pendant les vacances.

**Comment by fcabestre** [comment]
Miam

**Comment by fcabestre** [comment]
Oups, j'ai merdé

**Comment by davinkevin** [comment]
Ok pour moi aussi, on peut jumeler avec la session de #5 et cela nous ferai une belle soirée.

@ilaborie @fcabestre @vferries @batmat et autres => Il faudrait que l'on décide de la date. On choisi le 19 ? 

Cela serai ok pour toi @arnaudbos ?

**Comment by fcabestre** [comment]
C'est un jeudi, cool ! Parce que la prez d'@arnaudbos je ne veux pas la rater.

**Comment by ilaborie** [comment]
Super, si on évite les mardi c'est parfait pour moi

**Comment by arnaudbos** [comment]
Argh, je débarque mais le 19 octobre ça ne m'arrange pas du tout.
Si vous voulez rester sur un jeudi il y a le 9 novembre qui tombe après les vacances et qui me convient parfaitement.

**Comment by davinkevin** [comment]
:'(

Je regarde ce que l'on peut faire...

**Comment by arnaudbos** [comment]
Quoi de neuf 👨‍⚕️ ?

**Comment by davinkevin** [comment]
Il faut que l'on tente de voir si cela peut passer pour le 9...

**Comment by francoisroyer** [comment]
+1
@arnaudbos tu m'autoriserais à faire 10 mins en guest sur re-frame ou autre killer lib? :)

**Comment by arnaudbos** [comment]
Je comptais faire une ouverture rapide sur ClojureScript à la fin, re-frame me semble tout indiqué : be my guest :)
@davinkevin on peut grater 5mn ?

**Comment by francoisroyer** [comment]
Avec plaisir alors

**Comment by davinkevin** [comment]
Si on reste dans du raisonnable, pas de problème pour moi.

Le mer. 18 oct. 2017 à 15:44, François Royer <notifications@github.com> a
écrit :

**Comment by arnaudbos** [comment]
Je concède 5mn à @francoisroyer sur les 45 prévues et je passe la durée du talk à 50mn, comme ça on a les 10mn requises et on reste dans le raisonnable. Ça convient à tout le monde ?

**Comment by davinkevin** [comment]
No problem. 

Dans les faits, vous serez le dernière obstacles avant les pizzas 🍕, il faudra assumer 😉

**Comment by ltearno** [comment]
La soirée est programmée le 9 novembre.

@arnaudbos je n'ai pas ton email sous la main pour te prévenir, je te contacte dès que possible ;)

**Comment by davinkevin** [comment]
Hello @arnaudbos , il faudrait que l'on fasse un test pour la captation (la présentation sera filmé comme d'habitude) afin de vérifier que tes slides soient bien capturé.

Tu as quoi comme dispo pour faire un test ? Cela prend au max 10 minutes. Il faut juste que tu ai un compte Google Hangout. Dis moi quand c'est possible (de préférence, avant Jeudi 😉)

**Comment by arnaudbos** [comment]
Lundi ou mardi entre 8h et 17h.

J'ai un compte Google donc si c'est tout ce qu'il faut pas de soucis.

**Comment by davinkevin** [comment]
Ok, Lundi à 8h, c'est bon pour moi. Ajoute moi sur Hangout (nom point prénom @ gmail point com) et je lancerai tout cela demain matin
