### ISSUE TITLE
Après Docker, les Unikernels ?

### ISSUE THREAD

**Issue by ltearno** [ToulouseJug/call-for-paper#9]
### Le(s) speaker(s)

Alessio Coltellacci
Arnaud Tournier

### Description de votre conférence

Les architectures logicielles d'aujourd'hui reposent de plus en plus sur les conteneurs et les machines virtuelles. Avec tout ce que ces outils ont apporté, des problèmes perdurent : sécurité, temps de démarrage, poids des images (embarqué)...

Les unikernels apportent des réponses concrètes et les projets existants progressent dans leur maturité et leur niveau d'industrialisation.

Dans cette présentation, nous aborderons :

- ce qu'est un unikernel, les concepts associés et son fonctionnement,
- leurs champs d'application et l'écosytème,
- une démonstration,
- on s'appuiera sur la démo pour aborder les questionnements liés à cette nouvelle technologie (débuggage, profiling...).

### Informations diverses
* Thème, label : unikernel, docker, virtualisation, barbus
* Niveau de difficulté (débutant|confirmé) : intermédiaire
* Durée : 1h00 à 1h30
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): à partir de mai

**Comment by fcabestre** [comment]
Un peu de nouveauté au JUG \o/. Mais est-ce que vous allez vous donner un alibi JVM ?

**Comment by ltearno** [comment]
La jvm dans un unikernel? Pourquoi pas, si il y a moyen on en fera la démo.
À mon avis, avec jigsaw, en coupant la jvm subtilement, il devrait être
possible de lancer au moins un Hello World voir mini serveur web...
Si vous êtes sages (et que les dieux sont avec nous, c'est pas gagné ;)
Arnaud
